### ISSUE TITLE
Cannot build with react-native@0.43.1

### ISSUE THREAD

**Issue by huston007** [magicismight/react-native-root-siblings#4]
Getting this error:
```
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `react-native/Libraries/Components/StaticContainer` from `/Users
/username/Documents/work/projectname/node_modules/react-native-root-siblings/lib/AppRegistryInjection.js`: Module does no
t exist in the module map or in these directories:
  /Users/username/Documents/work/projectname/node_modules/react-native/Libraries/Components
,   /Users/username/node_modules/react-native/Libraries/Components
```

I performed a short research and found this renaming commit:
https://github.com/facebook/react-native/commit/57daad98f01b59fce9cb9bf663fd0b191c56b232

**Comment by OrangeFlavoredColdCoffee** [comment]
i got this . 

Unable to resolve module `react-native/Libraries/vendor/emitter/EventEmitter` from `/Users/litao/Project/auto-market/node_modules/react-native-root-siblings/lib/AppRegistryInjection.js`: Module does not exist in the module map or in these directories:
  /Users/litao/Project/auto-market/node_modules/react-native/Libraries/vendor/emitter

**Comment by bhoomika911** [comment]
I have the same issue. Can anyone help?

**Comment by OrangeFlavoredColdCoffee** [comment]
in react-native-root-siblings
change
import EventEmitter from 'react-native/Libraries/EventEmitter/EventEmitter';
to
import EventEmitter from 'react-native/Libraries/vendor/emitter/EventEmitter';

or
exchange  them

**Comment by Anishmprasad** [comment]
`Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `react-native/Libraries/vendor/emitter/EventEmitter` from `/Users/user1/Downloads/app/node_modules/react-native-root-siblings/lib/AppRegistryInjection.js`: Module does not exist in the module map or in these directories:
  /Users/user1/Downloads/app/node_modules/react-native/Libraries/vendor/emitter

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ResolutionRequest._resolveNodeDependency (/Users/user1/Downloads/app/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:394:11)
    at ResolutionRequest.resolveDependency (/Users/user1/Downloads/app/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:141:29)
    at dependencyNames.map.name (/Users/user1/Downloads/app/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (/Users/user1/Downloads/app/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:42)
    at module.read.then (/Users/user1/Downloads/app/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:172:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.ios.js`  99.0% (833/837), failed.`

**Comment by Pines-Cheng** [comment]
same error
